version: "3.9"
services:
  pangolin-newt-client:
    container_name: pangolin-newt-client
    image: fosrl/newt:1.1.3
    restart: unless-stopped
    network_mode: host
    environment:
      - PANGOLIN_ENDPOINT=${PANGOLIN_ENDPOINT}
      - NEWT_ID=${NEWT_ID}
      - NEWT_SECRET=${NEWT_SECRET}
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true